default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  idle_timeout: 60
  port: 5432

development:
  <<: *default
  adapter: postgresql
  database: employee_dev
  username: postgress
  password: postgress
  host: localhost
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: employee_test
  username: postgress
  password: postgress
  host: localhost
  port: 5432